language: elixir
elixir:
  - 1.3.3
otp_release:
  - 19.1

script:
  - MIX_ENV=test mix do compile, coveralls.json --exclude performance
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - bash <(curl -s https://codecov.io/bash)
